import type { MetadataRoute } from "next";

/**
 * Web App Manifest (App Router file convention).
 *
 * Served at `/manifest.webmanifest`. Enables installable / standalone
 * ("Add to Home Screen" / "Install app") behaviour like native apps — the
 * browser shows an install affordance and launches koku in its own window,
 * chrome-less, using the 刻 icon set generated by `scripts/generate-icons.mjs`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "刻 Koku — time & knowledge workspace",
    short_name: "Koku",
    description: "Mark the moment. Master your time. A local-first time tracker, notes, and knowledge graph.",
    id: "/dashboard",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#0a0a0a",
    theme_color: "#a43a30",
    categories: ["productivity", "utilities"],
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      { name: "Dashboard", url: "/dashboard", description: "Overview of your time" },
      { name: "Log time", url: "/log", description: "Track and review time entries" },
      { name: "Notes", url: "/notes", description: "Open your notes" },
      { name: "Reports", url: "/reports", description: "Analytics and reports" },
    ],
  };
}
